os: osx
osx_image: xcode9.4

matrix:
  include:
    - language: node_js
      os: linux
      node_js:
        - "10"

      install:
        - cd website
        - yarn
        - cd ..

      script:
        - cd website
        - yarn build
        - cd ..

      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          fqdn: fbflipper.com
          local-dir: website/build/flipper
          keep-history: true
          on:
            branch: master
    - language: node_js
      node_js:
        - "10"

      install:
        - yarn

      script:
        - yarn lint
        - yarn build --mac --version=$TRAVIS_BUILD_NUMBER

    - language: objective-c

      before_install:
        - rm -rf iOS/Sample/Pods
        - rm -f iOS/Sample/Podfile.lock
        - rm -f iOS/SampleSwift/Podfile.lock
        - pod repo update

      install:
        - cd iOS/Sample
        - rm -f Podfile.lock
        - pod install
        - cd ../SampleSwift
        - rm -f Podfile.lock
        - pod install
        - cd ../../

      script:
        - cd iOS/Sample
        - IPHONESIMULATOR=$(xcodebuild -showsdks | grep -o "iphonesimulator[0-9]\\+\\.[0-9]\\+$")
        - xcodebuild clean build -workspace Sample.xcworkspace -scheme Pods-Sample -sdk $IPHONESIMULATOR -quiet
        - cd ../SampleSwift
        - xcodebuild clean build -workspace SampleSwift.xcworkspace -scheme SampleSwift -sdk "$IPHONESIMULATOR" -quiet
    - language: android
      os: linux
      android:
        components:
          - tools
          - platform-tools
          - build-tools-27.0.3
          - android-27
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-27

        licenses:
          - android-sdk-preview-license-.+
          - android-sdk-license-.+
          - google-gdk-license-.+

      cache:
        directories:
          - $HOME/.gradle/wrapper
          - $HOME/.gradle/caches
          - android/third-party/external

      before_install:
        - yes | sdkmanager "platforms;android-27"
        - echo "y" | sdkmanager "cmake;3.6.4111459"
        - wget -q https://dl.google.com/android/repository/android-ndk-r17b-linux-x86_64.zip
        - mkdir -p temp-android-ndk
        - mv ./android-ndk-r17b-linux-x86_64.zip temp-android-ndk
        - cd temp-android-ndk
        - unzip -q android-ndk-r17b-linux-x86_64.zip
        - export ANDROID_NDK_HOME=`pwd`/android-ndk-r17b
        - export PATH=${PATH}:${ANDROID_NDK_HOME}
        - cd ../
      script:
        - ./gradlew :sample:build
