os: osx
osx_image: xcode9.3

matrix:
  include:
    - language: node_js
      node_js:
        - "8"

      install:
        - yarn
        - cd website
        - yarn
        - cd ..

      script:
        - yarn lint
        - yarn build --mac --version=$TRAVIS_BUILD_NUMBER
        - cd website
        - yarn build
        - cd ..

      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          fqdn: fbsonar.com
          local-dir: website/build/sonar
          keep-history: true
          on:
            branch: master
    - language: node_js
      node_js:
        - "10"

      install:
        - yarn
        - cd website
        - yarn
        - cd ..

      script:
        - yarn lint
        - yarn build --mac --version=$TRAVIS_BUILD_NUMBER
        - cd website
        - yarn build
        - cd ..

    - language: objective-c

      before_install:
        - pod repo update

      install:
        - cd iOS/Sample
        - pod install
        - cd ../../

      script:
        - cd iOS/Sample
        - xcodebuild clean build -workspace Sample.xcworkspace -scheme Pods-Sample -sdk iphonesimulator11.2

    - language: android
        os: linux
        android:
          components:
            # Uncomment the lines below if you want to
            # use the latest revision of Android SDK Tools
            # - tools
            # - platform-tools

            # The BuildTools version used by your project
            - build-tools-27.0.3

            # The SDK version used to compile your project
            - android-27

            # Additional components
            - extra-google-google_play_services
            - extra-google-m2repository
            - extra-android-m2repository
            - addon-google_apis-google-27

            # Specify at least one system image,
            # if you need to run emulator(s) during your tests
            - sys-img-armeabi-v7a-android-27
