os: osx
osx_image: xcode9.4

matrix:
  include:
    - language: node_js
      node_js:
        - "8"

      install:
        - yarn
        - cd website
        - yarn
        - cd ..

      script:
        - yarn lint
        - yarn build --mac --version=$TRAVIS_BUILD_NUMBER
        - cd website
        - yarn build
        - cd ..

      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          fqdn: fbsonar.com
          local-dir: website/build/sonar
          keep-history: true
          on:
            branch: master
    - language: node_js
      node_js:
        - "10"

      install:
        - yarn
        - cd website
        - yarn
        - cd ..

      script:
        - yarn lint
        - yarn build --mac --version=$TRAVIS_BUILD_NUMBER
        - cd website
        - yarn build
        - cd ..

    - language: objective-c

      before_install:
        - pod repo update

      install:
        - cd iOS/Sample
        - pod install
        - cd ../../

      script:
        - cd iOS/Sample
        - xcodebuild -showsdks
        - xcodebuild clean build -workspace Sample.xcworkspace -scheme Pods-Sample -sdk iphonesimulator11.4

    - language: android
      os: linux
      android:
        components:
          - tools
          - platform-tools
          - build-tools-27.0.3
          - android-27
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-27

        licenses:
          - android-sdk-preview-license-.+
          - android-sdk-license-.+
          - google-gdk-license-.+
      before_install:
        - yes | sdkmanager "platforms;android-27"
        - echo "y" | sdkmanager "cmake;3.6.4111459"
        - wget https://dl.google.com/android/repository/android-ndk-r17b-linux-x86_64.zip
        - mkdir -p temp-android-ndk
        - mv ./android-ndk-r17b-linux-x86_64.zip temp-android-ndk
        - cd temp-android-ndk
        - unzip android-ndk-r17b-linux-x86_64.zip
        - export ANDROID_NDK_HOME=`pwd`/android-ndk-r17b
        - export PATH=${PATH}:${ANDROID_NDK_HOME}
        - cd ../
      script:
        - ./gradlew :sample:build
      after_success:
        - rm -rf temp-android-ndk
      after_failure:
        - rm -rf temp-android-ndk
