os: osx
osx_image: xcode9.3

matrix:
  include:
    - language: node_js
      node_js:
        - "8"

      install:
        - yarn
        - cd website
        - yarn
        - cd ..

      script:
        - yarn lint
        - yarn build --mac --version=$TRAVIS_BUILD_NUMBER
        - cd website
        - yarn build
        - cd ..

      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          fqdn: fbsonar.com
          local-dir: website/build/sonar
          keep-history: true
          on:
            branch: master

    - language: objective-c

      before_install:
        - pod repo update

      install:
        - cd iOS/Sample
        - pod install
        - cd ../../

      script:
        - cd iOS/Sample
        - xcodebuild clean build -workspace Sample.xcworkspace -scheme Pods-Sample
