version: 2.0
jobs:
  build:
    docker:
      - image: circleci/android:api-28-ndk-r17b
    steps:
      - checkout
      - run:
          name: build and deploy
          command: |
            ./gradlew :sample:assembleDebug
            scripts/publish-android-snapshot.sh

workflows:
  version: 2
  build:
    jobs:
      - build
