version: 2.0
jobs:
  build:
    docker:
      - image: circleci/android:api-28-ndk-r17b
    steps:
      - checkout
      - run:
          name: build and deploy
          command: ./gradlew :sample:assembleDebug

  snapshot:
    docker:
      - image: circleci/android:api-28-ndk-r17b
    steps:
      - checkout
      - run:
          name: build and deploy
          command: scripts/publish-android-snapshot.sh

  release:
    docker:
      - image: circleci/android:api-28-ndk-r17b
    steps:
      - checkout
      - run:
          name: build and deploy
          command: scripts/publish-android-release.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - snapshot
          filters:
            branches:
              only: master
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
