name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: yarn
    - name: lint
      run: yarn lint
    - name: test
      run: yarn test
    - name: build linux
      if: matrix.os == 'ubuntu-latest'
      run: yarn build --linux
    - name: build macos
      if: matrix.os == 'macos-latest'
      run: yarn build --mac
    - name: build windows
      if: matrix.os == 'windows-latest'
      run: yarn build --win
    - name: upload linux artifact
      uses: actions/upload-artifact@v1
      if: matrix.os == 'ubuntu-latest'
      with:
        name: Flipper-linux.zip
        path: dist/Flipper-linux.zip
    - name: upload windows artifact
      uses: actions/upload-artifact@v1
      if: matrix.os == 'windows-latest'
      with:
        name: Flipper-win.zip
        path: dist/Flipper-win.zip
    - name: upload mac zip artifact
      uses: actions/upload-artifact@v1
      if: matrix.os == 'macos-latest'
      with:
        name: Flipper-mac.zip
        path: dist/Flipper-mac.zip
    - name: upload mac dmg artifact
      uses: actions/upload-artifact@v1
      if: matrix.os == 'macos-latest'
      with:
        name: Flipper-mac.dmg
        path: dist/Flipper-mac.dmg
